[project]
name = "autosync"
version = "0.1.0"
dependencies = [
  "termcolor >= 2.3.0",
  "tree_sitter < 0.22.0",
]
requires-python = ">= 3.11"

[tool.setuptools]
packages = ["autosync", "autosync.cpptranslator"]
package-dir = {"" = "src"}
