name: Auto-Sync
on:
  push:
    paths:
      - "suite/auto-sync/**"
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: suite/auto-sync/
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install auto-sync package
        run: |
          pip install .
      - name: Check formatting
        run: |
          python3.11 -m usort check src/autosync
          python3.11 -m black --check src/autosync
      - name: CppTranslator - Patch tests
        run: |
          python -m unittest discover src/autosync/cpptranslator/Tests/