name: Auto-Sync
on:
  push:
    paths:
      - "suite/auto-sync/**"
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install auto-sync package
        run: |
          cd suite/auto-sync/
          pip install -e .
      - name: Check formatting
        run: |
          ufmt check src
